name: Cloudformation template

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install

    - uses: actions/upload-artifact@v4
      with:
        name: case-study-1.0-SNAPSHOT-lambda-package.zip
        path: ./target/case-study-1.0-SNAPSHOT-lambda-package.zip

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Create S3 bucket
      run: aws s3 mb s3://cgkbucket --region us-east-1

    - name: Upload artifact zip to S3 bucket
      run: aws s3 cp ./target/case-study-1.0-SNAPSHOT-lambda-package.zip s3://cgkbucket/
      
    - name: Upload cloudformation template to S3 bucket
      run: aws s3 cp ./Deployment.yaml s3://cgkbucket/

  deploy:
    runs-on: ubuntu-latest
    environment: test
    needs: build

    steps: 
    - uses: actions/download-artifact@v4
      with:
        name: case-study-1.0-SNAPSHOT-lambda-package.zip
        path: ./target
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
          name: case-study-stack
          template:  https://cgkbucket.s3.amazonaws.com/Deployment.yaml
          no-fail-on-empty-changeset: "1"
          capabilities: CAPABILITY_IAM
          no-execute-changeset: "0"
          no-delete-failed-changeset: "0"
          disable-rollback: "0"
          termination-protection: "0"
